#!/bin/bash

# Load variables from .env file
export $(grep -v '^#' .env | xargs)

# Print the secret key (for verification)
echo "DJANGO_SECRET_KEY:" $DJANGO_SECRET_KEY

docker build -t procureinsight .
docker run -p 8080:8080 \
    -e DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME \
    procureinsight 