#!/bin/bash
docker build -t procureinsight .
docker tag procureinsight:latest us-west2-docker.pkg.dev/randd-418508/procure/procureinsight:0.0.0
docker push us-west2-docker.pkg.dev/randd-418508/procure/procureinsight:0.0.0